[package]
name = "cloudflare-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.61"
dyn-fmt = "0.4.0"

